# Generated by Django 4.2.7 on 2025-11-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Normalized unique key, e.g., 'mbs_ch_03'", max_length=255)),
                ('title', models.CharField(help_text='Title of the document', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Optional description of the document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['source', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the document source, e.g., 'Ginnie Mae MBS Guide'", max_length=255)),
                ('index_url', models.URLField(help_text='URL of the HTML page listing the PDFs', max_length=500)),
                ('parser_type', models.CharField(choices=[('ginnie_mae', 'Ginnie Mae'), ('usda', 'USDA'), ('custom', 'Custom')], default='custom', help_text='Determines which parser to use for this source', max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Whether this source is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Source',
                'verbose_name_plural': 'Document Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.URLField(help_text='URL of the PDF file', max_length=1000)),
                ('published_date', models.DateField(blank=True, help_text='Publication date of this version, if available', null=True)),
                ('pdf_hash', models.CharField(help_text='SHA-256 hash of the downloaded PDF file', max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When this version was fetched')),
                ('document', models.ForeignKey(help_text='The document this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, help_text='The current/latest version of this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_documents', to='documents.documentversion'),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(help_text='The source this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documentsource'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'pdf_hash'], name='documents_d_documen_06cf1d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['-fetched_at'], name='documents_d_fetched_519653_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'pdf_hash'), name='unique_document_version_hash'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source', 'slug'], name='documents_d_source__95be58_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('source', 'slug'), name='unique_document_source_slug'),
        ),
    ]
