# Generated by Django 4.2.7 on 2025-11-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Dash-separated unique identifier (e.g., 'ginnie-mae', 'usda')", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Display name for the parser type (e.g., 'Ginnie Mae')", max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Whether this parser type is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parser Type',
                'verbose_name_plural': 'Parser Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='documentsource',
            name='parser_type',
            field=models.ForeignKey(help_text='Determines which parser to use for this source', on_delete=django.db.models.deletion.PROTECT, related_name='document_sources', to='documents.parsertype'),
        ),
    ]
