# Generated by Django 4.2.7 on 2025-11-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_parsertype_alter_documentsource_parser_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentversion',
            name='unique_document_version_hash',
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('pdf_hash', None), _negated=True), fields=('document', 'pdf_hash'), name='unique_document_version_hash'),
        ),
    ]
