# Generated by Django 4.2.7 on 2025-11-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_documentversion_unique_document_version_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='pdf_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the downloaded PDF file', max_length=64, null=True),
        ),
    ]
