# Generated by Django 4.2.7 on 2025-11-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documentversion_pdf_hash'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentversion',
            name='unique_document_version_hash',
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('pdf_hash__isnull', True), _negated=True), models.Q(('pdf_hash', ''), _negated=True)), fields=('document', 'pdf_hash'), name='unique_document_version_hash'),
        ),
    ]
